// src/components/cover-image.tsx
import * as React from 'react'
import styled from 'styled-components'

import { aws } from '../aws'
import { BlogPost } from '../blog'
import { formatDateRange, ImageQuality } from '../common'
import { TakeHeight } from './helpers'

type ImageContainerProps = { height: string }
const ImageContainer = styled.div<ImageContainerProps>`
	width: 100%;
	height: ${props => props.height};

	position: fixed;
	z-index: -2;
`

type ImageProps = { src: string }
const Image = styled.div<ImageProps>`
	width: 100%;
	height: 100%;

	background-position: center;
	background-size: cover;
	background-image: url(${props => props.src});
`

const ImageOverlay = styled.div`
	width: 100%;
	height: 100%;
	box-shadow: inset 0 0 200px rgba(0, 0, 0, 0.5);
	background-color: rgba(0, 0, 0, 0.15);

	position: absolute;
	top: 0;
`

const ImageTitle = styled.h2`
	position: absolute;
	top: 0;

	width: 100%;
	height: 100%;
	transform: translate(0, 50%);
	text-align: center;
	margin: 0;

	color: #f9f9f9;
	font-size: 34px;
	font-weight: 300;
	text-shadow: 1px 1px #000;
`

const ImageSubtextContainer = styled.div`
	position: absolute;
	top: 0;

	width: 100%;
	height: 85vh;
	padding-bottom: 22px;
	box-sizing: border-box;

	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: flex-end;

	color: #f1f1f1;
`

const ImageSubtextItem = styled.p`
	font-size: 24px;
	font-weight: 300;
	font-style: italic;
	margin: 2px;
`

interface CoverImageProps {
	blogPost: BlogPost
	height: string
}

export const CoverImage = ({ blogPost, height }: CoverImageProps) => {
	const { title } = blogPost

	return (
		<>
			<ImageContainer height={height}>
				<Image
					src={aws.getImageUrl(
						blogPost.name,
						ImageQuality.FullHD,
						blogPost.coverImage
					)}
				/>
				<ImageOverlay />
				<ImageTitle>{title.toUpperCase()}</ImageTitle>
				<ImageSubtextContainer>
					<ImageSubtextItem>
						{formatDateRange(blogPost.dateRange)}
					</ImageSubtextItem>
					<ImageSubtextItem>{blogPost.trip}</ImageSubtextItem>
				</ImageSubtextContainer>
			</ImageContainer>
			<TakeHeight height={height} />
		</>
	)
}

// src/Components/CoverImage.vue
<template>
	<div class="cover-image-container">
		<image-component class="cover-image" v-if="image != null" :image="image" :quality="240p"> </image-component>

		<!-- Vignette -->
		<div style="position: absolute; top: 0px; height: 100%; width: 100%;
			background-color: rgba(0, 0, 0, 0.25); box-shadow: inset 0 0 200px rgba(0, 0, 0, 0.5);" ></div>

		<p class="main-text">  {{ mainText }}</p>
		<p class="sub-text" >{{ subText }}</p>
	</div>
</template>

<script>

import ImageComponent from "./Image.vue";

export default {
	components: {
		"image-component": ImageComponent
	},

	props: {
		image: {
			type: Object,
			required: true
		},

		mainText: {
			type: String,
			default: ""
		},

		// if this is set to true, then a 10p image is loaded first
		subText: {
			type: String,
			default: ""
		}
	}
};
</script>

<style lang="sass" scoped>
	$cover-image-height: 85vh;
	.cover-image-container {
		position: fixed;
		height: $cover-image-height;
		top: 0;
		transform: translateZ(0);
		z-index: -1000;

		width: 100%;
	}

	.cover-image {
		 width: 100%;
		 height: $cover-image-height !important;

		 min-height: 200px;
		 background-size: cover;
		 background-position: 50% 45%;
		 background-repeat: no-repeat;
	}

	.main-text {
		position: absolute;
		margin: 0;
		left: 50%;
		top: 50%;
		transform: translate(-50%, -50%);
		width: 95%;
		text-align: center;
		text-shadow: 1px 1px rgb(0, 0, 0);

		font-weight: 300;
		font-size: 34px;
		color: rgb(249, 249, 249);

		font-family: "Lato";
	}

	.sub-text {
		position: absolute;
		left: 50%;
		top: calc(100% - 54px);
		transform: translate(-50%, -50%);
		margin: auto;

		font-family: "Raleway";
		font-style: italic;
		font-weight: 300;
		font-size: 24px;

		color: rgb(205, 205, 205);
	}

	// in
	.cover-image > .blurry-image, .sharp-image {
		background-position: 50% 45%;
	}

</style>
