// src/Components/Navbar.vue
<template>
	<div id="navbar-container">
		<p id="navbar-header-text">{{ title }}</p>

		<div class="navbar-links">
			<p v-on:click="subLinkClicked(item, index)" :class="{ 'selected': index == selectedSubIndex, 'disabled': !item.enabled }" v-for="(index, item) in navbarLinks">{{ item.name.toUpperCase() }} </p>
		</div>

		<a href="https://instagram.com/fl.ai">
			<img class="instagram-icon" src="/icons/Instagram-Icon.png">
		</a>

		<div class="hamburger-menu">
			<img class="hamburger-menu-close-button" src="/icons/close.png" v-on:click="SetHamburgerMenuOpen(false)">
			<p v-on:click="subLinkClicked(item, index)" :class="{ 'selected': index == selectedSubIndex, 'disabled': !item.enabled }" v-for="(index, item) in navbarLinks">{{ item.name.toUpperCase() }} </p>
		</div>
		<img v-el:hamburger-menu-button  class="hamburger-menu-button" src="/icons/HamburgerMenuBlack.svg" v-on:click="SetHamburgerMenuOpen(true)">
	</div>
</template>

<script>
export default {
	data() {
		return {
			title: "flai",

			navbarLinks: [
					{ name: "home", enabled: false },
					{ name: "blog", enabled: true },
					{ name: "gear", enabled: false },
					{ name: "tours", enabled: true }
			],

			selectedSubIndex: 0,

			isHamburgerMenuOpen: false,
			isSmallNavbarForced: false
		};
	},

	ready: function() {
		$(window).resize(() => {
			this.SetHamburgerMenuOpen(false);
			this.updateNavbarSize();
		});

		$(window).scroll(() => {
			this.updateNavbarSize();
		});
	},

	methods: {
		updateNavbarSize: function() {
			if ($(document).scrollTop() > 0 || this.IsSmallNavbarForced()) {
				$("#navbar-container").addClass("shrink");
			}
			else if(!this.IsSmallNavbarForced()) {
				$("#navbar-container").removeClass("shrink");
			}
		},

		subLinkClicked: function(item, index) {
			if(!item.enabled) {
				return;
			}

			this.selectedSubIndex = index;

			if(index === 0) { // "home"
				this.$root.ChangePage("home-page", "/", { });
			}
			else if(index === 1) { // "blog"
				this.$root.ChangePage("blog-list-page", "/blog", { });
			}
			else if(index === 2) { // gear
				this.$root.ChangePage("gear-page", "/gear", { });
			}
			else if(index === 3) { // "tours"
				this.$root.ChangePage("tours-page", "/tours", { });
			}

			this.SetHamburgerMenuOpen(false);
		},

		ToggleHamburgerMenu: function() {
			this.SetHamburgerMenuOpen(!this.isHamburgerMenuOpen);
		},

		SetHamburgerMenuOpen: function(open) {
			this.isHamburgerMenuOpen = open;

			$(".hamburger-menu").toggleClass("open-hamburger-menu", open);
		},

		IsSmallNavbarForced: function() {
			const isHamburgerMenuVisible = $(".hamburger-menu-button").is(":visible");
			return this.isSmallNavbarForced || isHamburgerMenuVisible;
		}
	},

	events: {
		PageChanged: function(page) {
			const parts = page.split("-");
			parts.pop(); // remove last value from 'parts' (it is always 'page')

			this.isSmallNavbarForced = false;
			if(parts[0] === "blog") {
				this.selectedSubIndex = 1;
				this.isSmallNavbarForced = (parts[1] === "post"); // if blog-POST-page
			}
			else if(parts[0] === "gear") {
				this.selectedSubIndex = 2;
			}
			else if(parts[0] === "home") {
				this.selectedSubIndex = 0;
			}
			else if(parts[0] === "tours") {
				this.selectedSubIndex = 3;
			}

			this.updateNavbarSize();
			this.SetHamburgerMenuOpen(false);
		}
	}
};
</script>

<style lang="sass">

	@media all and (max-width: 615px) {
		.hamburger-menu-button {
			display: block !important;
		}

		.navbar-links {
			display: none !important;
		}
	}

	@media all and (min-width: 616px) {
		.hamburger-menu, .hamburger-menu-button {
			display: none  !important;
		}

		.navbar-links {
			display: block  !important;
		}
	}

	.instagram-icon {
		position: absolute;
		top: 50%;
		right: 16px;
		transform: translateY(-50%);
		transition: height 0.2s;

		height: 36%;
		min-height: 30px;

		&:hover {
			transform: translateY(-50%) scale(1.1333333333) ;
		}
	}

	.open-hamburger-menu {
		width: 100% !important;
		height: 100vh !important;
	}

	.hamburger-menu {
		width: 0px;
		height: 0px;
		background-color: rgb(32, 32, 32);
		transition: width .4s, height .4s;

		position: fixed;
		left: 0;
		top: 0;
		z-index: 1000;

		padding-top: 16px;
		overflow: hidden;

		p {
			display: block; margin-right: 8px;
			font-size: 22px;
			font-weight: 700;
			font-family: "Raleway";
			color: white;;
			opacity: 0.75;

			border-bottom: 2px solid transparent;;
			cursor: pointer;
			transition: opacity 0.15s ease-in-out;
			margin-left: 24px;
			width: auto;
			padding: 3px 1px;

			display: table;

			&:hover:not(.disabled):not(.selected) {
				opacity: 1;
				border-bottom: 2px solid rgba(255, 255, 255, 0.5);
			}

			&.selected {
				opacity: 1;
				font-weight: 800 !important;
				border-bottom: 2px solid white;
			}

			&.disabled {
				opacity: 0.3;
				cursor: default;
			}
		}

		.hamburger-menu-close-button {
			width: 24px;
			height: 24px;
			position: absolute;
			top: 38px;
			right: 24px;

			opacity: 0.75;
			cursor: pointer;

			&:hover {
				opacity: 0.9;
			}
		}
	}

	.hamburger-menu-button {
		height: 36%;
		min-height: 32px;

		position: absolute;
		top: 50%;
		transform: translateY(-50%);
		margin-top: 0px;
		margin-left: 8px;

		cursor: pointer;
	}

	.navbar-links {
		height: 100%;
		width: 100%;
		margin: auto;
		text-align: center;

		p {
			display: inline-block;
			font-weight: 600;
			font-family: "Raleway";
			color: black;
			opacity: 1;

			margin-right: 64px;

			cursor: pointer;
			transition: opacity 0.15s ease-in-out, border-bottom 0.2s ease-in-out;
			border-bottom: 2px solid transparent;
			padding-bottom: 3px;
			padding: 3px 1px;

			position: relative;
			top: 50%;
			margin-top: 0px;
			margin-bottom: 0px;
			transform: translateY(-50%);

			&:hover:not(.disabled) {
				opacity: 1;
				border-bottom: 2px solid rgba(0, 0, 0, 0.5);
			}

			&.selected:not(.disabled) {
				opacity: 1;
				border-bottom: 2px solid black;
			}

			&.disabled {
				color: rgba(0, 0, 0, 0.4);
				cursor: default;
			}

			&:last-child {
				/* last child should have no margin, so that the centering works properly */
				margin-right: 0px;
			}
		}
	}

	.header-divider {
	     border-left:1px solid hsl(0, 0, 60);
	     border-right:1px solid hsl(0, 0, 60);
	     height: 32px;
	     margin-bottom: -10px;
		 display: inline-block;
	}

	$font-stack: 'Yanone Kaffeesatz', 'Segoe UI';

	#navbar-container {
		width: 100%;
		height: 118px;
		background-color: white;
		top: 0;
		font-size: 20px;
		z-index: 100;

		transition: height 0.2s, font-size 0.2s;
		position: fixed;

		&.shrink {
			height: 40px;
			position: fixed;
			font-size: 16px;

		//	border-bottom: solid 1px rgba(200, 200, 200, 0.5);
		}
	}

	#navbar-header-text {
		color: rgb(64, 64, 64);
		font-size: 50px;
		font-family: "Lato";
		font-weight: 300;

		width: 100%;
		height: 100%;
		text-align: center;
		margin: auto;
		position: absolute;
		top: -3px;
		display: none;
	}
</style>


<style lang="sass" scoped>
	$font-stack: Open Sans;
    $list-padding: 3px;
    $list-height: 40px;
	$list-border-radius: 5px;
	$list-background-color: rgb(64, 64, 64); // todo: this should be in "general.scss" or something

	#route-selection-list-container {
		width: 510px;
		margin-left: auto;
		margin-right: 300px;

		margin-top: -32px;
	}

    #route-selection-list {
        list-style-type: none;
        text-align: right;
        margin: 0px;

        display: inline-block;

        /* 3px == real padding. 7px == 3px + 4px. 4px because no fucking clue why it's needed on bottom */
        padding: $list-padding $list-padding calc(#{$list-padding} + 4px);
        height: $list-height;

        border-radius: $list-border-radius;
		float: right;
    }

    #route-selection-list li {
        float: left;

        width: auto;
        height: auto;

        text-align: center;
        vertical-align: middle;
        display: table;

		margin: 0px 14px;
        transition: background-color 0.3s ease-in-out;
	}

	#route-selection-list p {
		height: 100%;

		font-size: 1.5em;
		font-family: $font-stack;
		font-weight: normal;
		color: rgb(128, 128, 128);
	}

	#route-selection-list .selected {
		background-color: rgb(64, 64, 64);
	}
</style>

// src/components/Navbar.tsx
import * as React from 'react';
import styled, { css } from 'styled-components';
import withProps from 'styled-components-ts';

import InstagramIcon from '../assets/icons/instagram.svg';
import { TakeHeight } from './helpers';
import history from '../history';
import paths from '../paths';

type Link = { name: string, url: string, enabled: boolean };
const links: Link[] = [
	{ name: 'home', url: paths.home, enabled: true },
	{ name: 'blog', url: paths.blogList, enabled: true },
	{ name: 'gear', url: paths.gear, enabled: false },
	{ name: 'tours', url: paths.tours, enabled: true }
];

const NAVBAR_HEIGHT = 118;
type NavContainerProps = { shrink: boolean };
const NavContainer = withProps<NavContainerProps>(styled.div)`
	display: grid;
	grid-template-columns: 0px auto 0px; /* hack because of NavImage... */

	position: fixed;
	top: 0px;
	width: 100%;
	height: ${props => props.shrink ? '40px' : `${NAVBAR_HEIGHT}px`};

	font-size: ${props => props.shrink ? '16px' : '20px'};
	background-color: white;
	z-index: 1;

	transition: height 0.3s, font-size 0.3s;
`;

const NavLinksContainer = styled.div`
	align-self: center;
	align-content: center;
	text-align: center;

	grid-column: 2;
`;

type NavLinkProps = { selected: boolean, enabled: boolean };
const NavLink = withProps<NavLinkProps>(styled.a)`
	font-weight: 600;

	text-decoration: none;
	color: black;
	opacity: ${props => props.enabled ? 1 : 0.4};
	border-bottom: 2px solid ${props => props.selected ? 'black' : 'transparent'};
	transition: border-bottom 0.3s;

	pointer-events: ${props => props.enabled ? 'inherit' : 'none'};
	margin: 0px 32px;
	padding: 3px 1px;

	&:hover {
		${props => (props.enabled && !props.selected)
			? css`border-bottom: 2px solid rgba(0, 0, 0, 0.5);`
			: ''
		};
	}
`;

const NavImage = styled.img`
	position: absolute;
	top: 50%;
	transform: translateY(-50%);

	height: 36%;
	min-height: 30px;
	transition: transform 0.2s;

	&:hover {
		transform: translateY(-50%) scale(1.2);
	}
`;

type NavSideButtonProps = { href: string, src: string, side?: 'right' | 'left' };
const NavSideButton = ({ href, src, side = 'right' }: NavSideButtonProps) => {
	const style = (side === 'right') ? { right: '16px' } : { left: '16px' };
	return (
		<a href={href}>
			<NavImage style={style} src={src} />
		</a>
	);
};

const Link = (props: { link: Link, selected: boolean }) => (
	<NavLink 
		href={`/${props.link.name}`} 
		selected={props.selected} 
		enabled={props.link.enabled}
		onClick={e => { e.preventDefault(); history.push(`${props.link.url}`); }}
	>
		{props.link.name.toUpperCase()}
	</NavLink>
);

const isLinkSelected = (link: Link) => (link.url === '/')
	? history.location.pathname === '/'
	: history.location.pathname.startsWith(link.url);

interface NavbarProps { forceShrinked: boolean; }
interface NavbarState { shrink: boolean; }
class Navbar extends React.Component<NavbarProps, NavbarState> {
	state = {
		shrink: false,
	};

	handleScroll = () => {
		const shrink = window.scrollY > 0;
		this.setState({ shrink });
	}

	componentDidMount() {
		window.addEventListener('scroll', this.handleScroll);
	}

	componentWillUnmount() {
		window.removeEventListener('scroll', this.handleScroll);
	}

	render() {
		const shrink = this.state.shrink || this.props.forceShrinked;
		return (
			<>
				<NavContainer shrink={shrink}>
					<NavLinksContainer>
						{links.map(link => <Link key={link.name} link={link} selected={isLinkSelected(link)} />)}
					</NavLinksContainer>

					<NavSideButton side='right' href='https://instagram.com/fl.ai' src={InstagramIcon} />

				</NavContainer>
				<TakeHeight height={`${NAVBAR_HEIGHT}px`} />
			</>
		);
	}
}

export default Navbar;
